// One-time generator for the Web-Push VAPID keypair.
//
//   node scripts/gen-vapid.mjs
//
// VAPID keys are how a push service (Apple/Google/Mozilla) verifies that a push
// genuinely came from *your* server. The PUBLIC key is safe in the browser; the
// PRIVATE key must stay server-side only.
//
// This writes the keys straight into .env.local (gitignored) and prints only the
// public key. Copy the server values from .env.local into your Vercel project
// env — never paste the private key into a chat or commit it.

import webpush from 'web-push';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env.local');

const existing = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
if (/^VAPID_PRIVATE_KEY=/m.test(existing)) {
  console.log('\n⚠️  VAPID keys already exist in .env.local — leaving them untouched.');
  console.log('    Delete the VAPID_* lines first if you really want to rotate them.\n');
  process.exit(0);
}

const { publicKey, privateKey } = webpush.generateVAPIDKeys();
const subject = process.env.VAPID_SUBJECT || 'mailto:shreyaan.datta@gmail.com';

const block = [
  '',
  '# --- Web Push (VAPID) — generated by scripts/gen-vapid.mjs ---',
  `VITE_VAPID_PUBLIC_KEY=${publicKey}`, // client (publishable)
  `VAPID_PUBLIC_KEY=${publicKey}`,      // server
  `VAPID_PRIVATE_KEY=${privateKey}`,    // server ONLY — keep secret
  `VAPID_SUBJECT=${subject}`,
  '',
].join('\n');

writeFileSync(envPath, existing.replace(/\s*$/, '') + '\n' + block);

console.log('\n✅ VAPID keys written to .env.local');
console.log('   Public key (safe to share):\n   ' + publicKey);
console.log('\nNext: copy VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT and a');
console.log('CRON_SECRET into your Vercel project env (the private key only goes there).\n');
